/* Photos — Unsplash vérifiées 200 (curl, 20/08/2026). Nouvelle marque :
   aucune photo réelle de chantier disponible, tout est illustratif. */
export const PHOTOS = {
  heroHaussmannien: "https://images.unsplash.com/photo-1634586648651-f1fb9ec10d90?q=80&w=1600&auto=format&fit=crop",
  sejourApres: "https://images.unsplash.com/photo-1724582586529-62622e50c0b3?q=80&w=1600&auto=format&fit=crop",
  sejourAvant: "https://images.unsplash.com/photo-1649083048770-82e8ffd80431?q=80&w=1600&auto=format&fit=crop",
  salonMinimal2: "https://images.unsplash.com/photo-1724582586458-a51791349977?q=80&w=1600&auto=format&fit=crop",

  detailParquet: "/photos/chantiers/chParquetVitrifie.jpeg",
  parquetGros: "https://images.unsplash.com/photo-1761053133165-0f3acdaf1770?q=80&w=1600&auto=format&fit=crop",

  cuisineSurMesure: "/photos/chantiers/chCuisineCremeIlot.jpeg",
  cuisineDetail: "https://images.unsplash.com/photo-1714860534425-7ce04e013dec?q=80&w=1600&auto=format&fit=crop",

  salleBainBeton: "/photos/chantiers/chSdbCarreauxCiment.jpeg",
  betonCireDetail: "https://images.unsplash.com/photo-1560780552-ba54683cb263?q=80&w=1600&auto=format&fit=crop",

  chantierRenovation: "/photos/chantiers/chCloisonsPlaco.jpeg",
  chantierIsolation: "/photos/chantiers/chIsolationCombles.jpeg",

  planArchitecte: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1600&auto=format&fit=crop",
  devisDetail: "https://images.unsplash.com/photo-1542621334-a254cf47733d?q=80&w=1600&auto=format&fit=crop",
  grosOeuvre: "/photos/chantiers/chSurelevationBrique.jpeg",

  outilsArtisan: "https://images.unsplash.com/photo-1676311396794-f14881e9daaa?q=80&w=1600&auto=format&fit=crop",
  visiteTechnique: "https://images.unsplash.com/photo-1606676539940-12768ce0e762?q=80&w=1600&auto=format&fit=crop",

  detailMoulure: "https://images.unsplash.com/photo-1722942429838-8a51e60ca7b8?q=80&w=1600&auto=format&fit=crop",

  cuisineIlot: "https://images.unsplash.com/photo-1502005097973-6a7082348e28?q=80&w=1600&auto=format&fit=crop",
  salleBainBaignoire: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=1600&auto=format&fit=crop",
  salleBainMiroir: "https://images.unsplash.com/photo-1661107259637-4e1c55462428?q=80&w=1600&auto=format&fit=crop",
  salonCanape: "https://images.unsplash.com/photo-1724582586495-d050726cf354?q=80&w=1600&auto=format&fit=crop",
  parquetDetail2: "https://images.unsplash.com/photo-1783791995743-cf144ee771f1?q=80&w=1600&auto=format&fit=crop",
  chantierCuisineProtection: "https://images.unsplash.com/photo-1618832515490-e181c4794a45?q=80&w=1600&auto=format&fit=crop",
  chantierEchelle: "https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?q=80&w=1600&auto=format&fit=crop",
  cheminee2: "https://images.unsplash.com/photo-1722152257494-e26f08d5bb0d?q=80&w=1600&auto=format&fit=crop",

  /* Photos de référence — appartement réel (fourni par le client, 25/08/2026).
     Illustration de niveau de finition, pas des chantiers ARCHI PILOTE RÉNOVATION. */
  refChambreBalcon: "/photos/ref/refChambreBalcon.png",
  refChambreTeteLitVelours: "/photos/ref/refChambreTeteLitVelours.jpeg",
  refSalleBainMarbreNoir: "/photos/ref/refSalleBainMarbreNoir.jpeg",
  refChambreArmoireBlanche: "/photos/ref/refChambreArmoireBlanche.jpeg",
  refCuisineSejour: "/photos/ref/refCuisineSejour.jpeg",
  refSalleBainMarbreClair: "/photos/ref/refSalleBainMarbreClair.jpeg",
  refChambreDoreeJaune: "/photos/ref/refChambreDoreeJaune.jpeg",
  refSalonBalconRue: "/photos/ref/refSalonBalconRue.jpeg",

  /* Photos de CHANTIERS RÉELS — fournies par le client (Ilann, 27/08/2026),
     réalisations des équipes partenaires du groupe. Sélection et légendes
     rédigées d'après les pixels, image par image. Registre : docs/REGISTRE-MEDIAS.md */
  chParquetVitrifie: "/photos/chantiers/chParquetVitrifie.jpeg",
  chMenuiserieClaustra: "/photos/chantiers/chMenuiserieClaustra.jpeg",
  chCharpenteInterieur: "/photos/chantiers/chCharpenteInterieur.jpeg",
  chCharpenteLevee: "/photos/chantiers/chCharpenteLevee.jpeg",
  chLitCabane: "/photos/chantiers/chLitCabane.jpeg",
  chRavalementArdoise: "/photos/chantiers/chRavalementArdoise.jpeg",
  chSdbCarreauxCiment: "/photos/chantiers/chSdbCarreauxCiment.jpeg",
  chSdbBaignoireTeck: "/photos/chantiers/chSdbBaignoireTeck.jpeg",
  chCloisonsPlaco: "/photos/chantiers/chCloisonsPlaco.jpeg",
  chSurelevationBrique: "/photos/chantiers/chSurelevationBrique.jpeg",
  chBibliotheque: "/photos/chantiers/chBibliotheque.jpeg",
  chIsolationCombles: "/photos/chantiers/chIsolationCombles.jpeg",
  chCuisineCremeIlot: "/photos/chantiers/chCuisineCremeIlot.jpeg",
  chCuisineTerracotta: "/photos/chantiers/chCuisineTerracotta.jpeg",
  chCuisineSauge: "/photos/chantiers/chCuisineSauge.jpeg",
  chCuisineBlancheU: "/photos/chantiers/chCuisineBlancheU.jpeg",

  /* Second lot de photos de CHANTIERS RÉELS — fournies par le client (Ilann, 30/08/2026),
     réalisations des équipes partenaires du groupe, plusieurs chantiers distincts
     (dont un local commercial). Registre : docs/REGISTRE-MEDIAS.md */
  chDemolitionCloisonBoisPlatre: "/photos/chantiers/chDemolitionCloisonBoisPlatre.jpeg",
  chDemolitionMursDecapes: "/photos/chantiers/chDemolitionMursDecapes.jpeg",
  chDemolitionOuvertureCouloir: "/photos/chantiers/chDemolitionOuvertureCouloir.jpeg",
  chPortiqueAcierAngleGaine: "/photos/chantiers/chPortiqueAcierAngleGaine.jpeg",
  chPoutreAcierSoudure: "/photos/chantiers/chPoutreAcierSoudure.jpeg",
  chPoutreAcierMurDegarni: "/photos/chantiers/chPoutreAcierMurDegarni.jpeg",
  chPortiqueAcierAngleFenetre: "/photos/chantiers/chPortiqueAcierAngleFenetre.jpeg",
  chPoteauAcierPlatinePied: "/photos/chantiers/chPoteauAcierPlatinePied.jpeg",
  chBibliothequeRadiateurIntegre: "/photos/chantiers/chBibliothequeRadiateurIntegre.jpeg",
  chDressingLaqueBlancPoigneesBois: "/photos/chantiers/chDressingLaqueBlancPoigneesBois.jpeg",
  chDressingLaqueBlancCouloirPlans: "/photos/chantiers/chDressingLaqueBlancCouloirPlans.jpeg",
  chNicheBibliothequeCouloir: "/photos/chantiers/chNicheBibliothequeCouloir.jpeg",
  chPorteCoulissanteClaustraChene2: "/photos/chantiers/chPorteCoulissanteClaustraChene2.jpeg",
  chBibliothequeCouloirTrappe: "/photos/chantiers/chBibliothequeCouloirTrappe.jpeg",
  chEnsembleRangementRadiateurClaustra: "/photos/chantiers/chEnsembleRangementRadiateurClaustra.jpeg",
  chCuisineBleuCanardBrillante: "/photos/chantiers/chCuisineBleuCanardBrillante.jpeg",
  chOuvertureImposteVitreeDoubleParte: "/photos/chantiers/chOuvertureImposteVitreeDoubleParte.jpeg",
  chEscalierBoisFlottantVueBas: "/photos/chantiers/chEscalierBoisFlottantVueBas.jpeg",
  chOptiquePresentoirsMuraux: "/photos/chantiers/chOptiquePresentoirsMuraux.jpeg",
  chOptiqueAccueilFinition: "/photos/chantiers/chOptiqueAccueilFinition.jpeg",
  chEscalierBoisFlottantPalier: "/photos/chantiers/chEscalierBoisFlottantPalier.jpeg",
  chOptiqueComptoirAccueilFini: "/photos/chantiers/chOptiqueComptoirAccueilFini.jpeg",
  chOptiqueComptoirCarcasseBrute: "/photos/chantiers/chOptiqueComptoirCarcasseBrute.jpeg",
  chHabillageMdfSousPente: "/photos/chantiers/chHabillageMdfSousPente.jpeg",
  chDressingSousPenteBlancTiroirs: "/photos/chantiers/chDressingSousPenteBlancTiroirs.jpeg",
  chDressingSousPenteVeluxPoigneesNoires: "/photos/chantiers/chDressingSousPenteVeluxPoigneesNoires.jpeg",
  chCuisineBlancheElectromenagerLG: "/photos/chantiers/chCuisineBlancheElectromenagerLG.jpeg",
  chDressingMdfBrutNiche: "/photos/chantiers/chDressingMdfBrutNiche.jpeg",
  chSdbVasquesPoseMeubleBeige: "/photos/chantiers/chSdbVasquesPoseMeubleBeige.jpeg",
  chBibliothequesMdfBrutOuvertes: "/photos/chantiers/chBibliothequesMdfBrutOuvertes.jpeg",
  chComptoirBarColonneFonteCarreauxAnciens: "/photos/chantiers/chComptoirBarColonneFonteCarreauxAnciens.jpeg",
  chComptoirBarMouluresFinition: "/photos/chantiers/chComptoirBarMouluresFinition.jpeg",
  chCuisinePlanNoirFacadesCremeVelux: "/photos/chantiers/chCuisinePlanNoirFacadesCremeVelux.jpeg",
  chPlacagesNoyerEnAttente: "/photos/chantiers/chPlacagesNoyerEnAttente.jpeg",
  chDressingNoyerCarcasseTringle: "/photos/chantiers/chDressingNoyerCarcasseTringle.jpeg",
  chOssatureBoisComptoirLocalCommercial: "/photos/chantiers/chOssatureBoisComptoirLocalCommercial.jpeg",
  chDressingBufetNoyerMoulures1: "/photos/chantiers/chDressingBufetNoyerMoulures1.jpeg",
  chDressingNoyerCarcassesVides: "/photos/chantiers/chDressingNoyerCarcassesVides.jpeg",
  chDressingNoyerMoulures2: "/photos/chantiers/chDressingNoyerMoulures2.jpeg",
  chDressingBufetNoyerPorteBleue: "/photos/chantiers/chDressingBufetNoyerPorteBleue.jpeg",
  chGrilleAerationMdfSurMesure: "/photos/chantiers/chGrilleAerationMdfSurMesure.jpeg",
  chDetailTiroirCoulisses: "/photos/chantiers/chDetailTiroirCoulisses.jpeg",
  chCuisineSejourParquetChevrons: "/photos/chantiers/chCuisineSejourParquetChevrons.jpeg",
  chDressingBufetNoyerMoulures3: "/photos/chantiers/chDressingBufetNoyerMoulures3.jpeg",
  chDressingBrutKraftSpots: "/photos/chantiers/chDressingBrutKraftSpots.jpeg",
  chCouloirParquetChevronsPortesOuvertes: "/photos/chantiers/chCouloirParquetChevronsPortesOuvertes.jpeg",
  chPlacardTableauElectriqueIntegre: "/photos/chantiers/chPlacardTableauElectriqueIntegre.jpeg",
  chPlancherSolivesBeton1: "/photos/chantiers/chPlancherSolivesBeton1.jpeg",
  chPlancherSolivesBeton2: "/photos/chantiers/chPlancherSolivesBeton2.jpeg",
  chSousCouchePanneauxOSB: "/photos/chantiers/chSousCouchePanneauxOSB.jpeg",
  chIsolationPhoniqueGranulesPlancher: "/photos/chantiers/chIsolationPhoniqueGranulesPlancher.jpeg",
  chPlacardKraftCouloirEtroit: "/photos/chantiers/chPlacardKraftCouloirEtroit.jpeg",
  chCuisineBlancheBrillanteMarbre: "/photos/chantiers/chCuisineBlancheBrillanteMarbre.jpeg",
  chCuisineAnthraciteCarreauxCiment: "/photos/chantiers/chCuisineAnthraciteCarreauxCiment.jpeg",
  chEncadrementBoisPorteMiroirAtelier: "/photos/chantiers/chEncadrementBoisPorteMiroirAtelier.jpeg",
  chBibliothequePanneauxMoulures: "/photos/chantiers/chBibliothequePanneauxMoulures.jpeg",
  chVerriereInterieurePentagonale: "/photos/chantiers/chVerriereInterieurePentagonale.jpeg",
  chRangementSousPenteCombles: "/photos/chantiers/chRangementSousPenteCombles.jpeg",
  chEtagereBureauNicheRadiateur: "/photos/chantiers/chEtagereBureauNicheRadiateur.jpeg",
  chEtagereMuraleContreplaque: "/photos/chantiers/chEtagereMuraleContreplaque.jpeg",
  chCuisineNoireBrillantePoigneesCuivrees: "/photos/chantiers/chCuisineNoireBrillantePoigneesCuivrees.jpeg",
  chDressingBrutTiroirsRoulettes: "/photos/chantiers/chDressingBrutTiroirsRoulettes.jpeg",
  chPlacardCompteurElectriqueArrondi: "/photos/chantiers/chPlacardCompteurElectriqueArrondi.jpeg",
  chDressingCarcasseChantEnBois: "/photos/chantiers/chDressingCarcasseChantEnBois.jpeg",

  /* Troisième lot — photos réelles fournies par le client (Ilann, 30/08/2026),
     continuations vérifiées de projets déjà confirmés réels (opticien, dressings
     noyer haussmannien, comptoir bar colonne fonte, structure acier Tridenso,
     plancher/isolation). Le reste du lot (photographie immobilière mise en scène,
     un chantier d'hôtel sans rapport, images Pinterest) a été écarté. */
  chPortiqueAcierAngleMurDegarni2: "/photos/chantiers/chPortiqueAcierAngleMurDegarni2.jpeg",
  chPoutreAcierPlafondMurDegarni: "/photos/chantiers/chPoutreAcierPlafondMurDegarni.jpeg",
  chPoutreAcierSoudureAngle2: "/photos/chantiers/chPoutreAcierSoudureAngle2.jpeg",
  chPoutreAcierMurPierreApparente: "/photos/chantiers/chPoutreAcierMurPierreApparente.jpeg",
  chPoteauAcierScelleGravats: "/photos/chantiers/chPoteauAcierScelleGravats.jpeg",
  chOptiqueComptoirCarcasseBrute2: "/photos/chantiers/chOptiqueComptoirCarcasseBrute2.jpeg",
  chOptiquePresentoirsVitrine: "/photos/chantiers/chOptiquePresentoirsVitrine.jpeg",
  chOptiqueComptoirAccueilFini2: "/photos/chantiers/chOptiqueComptoirAccueilFini2.jpeg",
  chDressingNoyerMouluresAngle1: "/photos/chantiers/chDressingNoyerMouluresAngle1.jpeg",
  chDressingNoyerMouluresFenetre: "/photos/chantiers/chDressingNoyerMouluresFenetre.jpeg",
  chDressingNoyerBufetMoulures4: "/photos/chantiers/chDressingNoyerBufetMoulures4.jpeg",
  chPlacagesNoyerEnAttente2: "/photos/chantiers/chPlacagesNoyerEnAttente2.jpeg",
  chDressingNoyerOuvertOutils: "/photos/chantiers/chDressingNoyerOuvertOutils.jpeg",
  chComptoirBarColonneFonteVueLarge: "/photos/chantiers/chComptoirBarColonneFonteVueLarge.jpeg",
  chComptoirBarEtageresOutils: "/photos/chantiers/chComptoirBarEtageresOutils.jpeg",
  chOssatureBoisComptoirCommercial2: "/photos/chantiers/chOssatureBoisComptoirCommercial2.jpeg",
  chSousCouchePanneauxOSB2: "/photos/chantiers/chSousCouchePanneauxOSB2.jpeg",
  chPlancherSolivesBoisRangees: "/photos/chantiers/chPlancherSolivesBoisRangees.jpeg",
  chDemolitionBoiseriesHaussmannien: "/photos/chantiers/chDemolitionBoiseriesHaussmannien.jpeg",
  chIsolationPhoniqueGranulesPlancher2: "/photos/chantiers/chIsolationPhoniqueGranulesPlancher2.jpeg",

  /* Reste du même lot (30/08/2026) — photos homogènes avec le style chantier
     réel déjà établi (démolition, structure, menuiserie, cuisines, terrasses,
     façades). Exclus du même lot : photographie immobilière mise en scène,
     un chantier d'hôtel sans rapport, images de charpente façon Pinterest,
     et les plans techniques nominatifs. */
  chMenuiserieInstallationPanneauMural: "/photos/chantiers/chMenuiserieInstallationPanneauMural.jpeg",
  chEtagereBoisAssemblageAtelier: "/photos/chantiers/chEtagereBoisAssemblageAtelier.jpeg",
  chCouloirPorteAccordeonBois: "/photos/chantiers/chCouloirPorteAccordeonBois.jpeg",
  chDressingOuvertTiroirsEntrouverts: "/photos/chantiers/chDressingOuvertTiroirsEntrouverts.jpeg",
  chEtagereCoinFenetreBrute: "/photos/chantiers/chEtagereCoinFenetreBrute.jpeg",
  chArcheEncadrementBoisChantier: "/photos/chantiers/chArcheEncadrementBoisChantier.jpeg",
  chVasqueBoisMuraleChantier: "/photos/chantiers/chVasqueBoisMuraleChantier.jpeg",
  chCaissonTiroirsBoisAngle: "/photos/chantiers/chCaissonTiroirsBoisAngle.jpeg",
  chEtagereCoinCableApparent: "/photos/chantiers/chEtagereCoinCableApparent.jpeg",
  chFacadeRavalementEchafaudage1: "/photos/chantiers/chFacadeRavalementEchafaudage1.jpeg",
  chDressingEscalierArriereplan: "/photos/chantiers/chDressingEscalierArriereplan.jpeg",
  chEtagereChantierEchelle: "/photos/chantiers/chEtagereChantierEchelle.jpeg",
  chDressingEscalierArriereplan2: "/photos/chantiers/chDressingEscalierArriereplan2.jpeg",
  chCharpenteParpaingConstruction: "/photos/chantiers/chCharpenteParpaingConstruction.jpeg",
  chTerrassePiscineBoisVue1: "/photos/chantiers/chTerrassePiscineBoisVue1.jpeg",
  chTerrassePiscineMaisonVue: "/photos/chantiers/chTerrassePiscineMaisonVue.jpeg",
  chCharpenteToitureOSBChantier: "/photos/chantiers/chCharpenteToitureOSBChantier.jpeg",
  chCharpenteMaisonEchafaudage: "/photos/chantiers/chCharpenteMaisonEchafaudage.jpeg",
  chTerrasseBoisTransatsVue: "/photos/chantiers/chTerrasseBoisTransatsVue.jpeg",
  chTerrasseBoisEscaliersMobilier: "/photos/chantiers/chTerrasseBoisEscaliersMobilier.jpeg",
  chTerrasseBoisPiscineCourbe: "/photos/chantiers/chTerrasseBoisPiscineCourbe.jpeg",
  chTerrasseBoisPiscineChamps: "/photos/chantiers/chTerrasseBoisPiscineChamps.jpeg",
  chLivraisonPanneauPrefabGrue: "/photos/chantiers/chLivraisonPanneauPrefabGrue.jpeg",
  chNicheArrondieBoisEclairage: "/photos/chantiers/chNicheArrondieBoisEclairage.jpeg",
  chFacadeRavalementVillage: "/photos/chantiers/chFacadeRavalementVillage.jpeg",
  chCouloirPorteBoisModerne: "/photos/chantiers/chCouloirPorteBoisModerne.jpeg",
  chCouloirPortesBoisJumelles: "/photos/chantiers/chCouloirPortesBoisJumelles.jpeg",
  chFacadeRavalementEchafaudage2: "/photos/chantiers/chFacadeRavalementEchafaudage2.jpeg",
  chNicheArrondieCouloirBacklight: "/photos/chantiers/chNicheArrondieCouloirBacklight.jpeg",
  chDressingArrondiCouloirParquet1: "/photos/chantiers/chDressingArrondiCouloirParquet1.jpeg",
  chDressingArrondiCouloirParquet2: "/photos/chantiers/chDressingArrondiCouloirParquet2.jpeg",
  chParquetChevronsPosePiece: "/photos/chantiers/chParquetChevronsPosePiece.jpeg",
  chDressingProcheToilettes: "/photos/chantiers/chDressingProcheToilettes.jpeg",
  chDetailPoigneePorteMain1: "/photos/chantiers/chDetailPoigneePorteMain1.jpeg",
  chDetailPoigneePorteMain2: "/photos/chantiers/chDetailPoigneePorteMain2.jpeg",
  chDemolitionLattisPlatreChantier1: "/photos/chantiers/chDemolitionLattisPlatreChantier1.jpeg",
  chDemolitionLattisPlatreChantier2: "/photos/chantiers/chDemolitionLattisPlatreChantier2.jpeg",
  chDemolitionGravatsChantier: "/photos/chantiers/chDemolitionGravatsChantier.jpeg",
  chDressingBlancOuvertChantier1: "/photos/chantiers/chDressingBlancOuvertChantier1.jpeg",
  chDressingBlancOuvertChantier2: "/photos/chantiers/chDressingBlancOuvertChantier2.jpeg",
  chNicheBoisPortesArquees: "/photos/chantiers/chNicheBoisPortesArquees.jpeg",
  chCouloirBoisGaleriesBanc: "/photos/chantiers/chCouloirBoisGaleriesBanc.jpeg",
  chCuisineBlancheFinieIlot: "/photos/chantiers/chCuisineBlancheFinieIlot.jpeg",
  chDressingSousPenteBlancPortes: "/photos/chantiers/chDressingSousPenteBlancPortes.jpeg",
  chCouloirBoisEscalierVue: "/photos/chantiers/chCouloirBoisEscalierVue.jpeg",
  chDressingBlancTiroirsOuverts: "/photos/chantiers/chDressingBlancTiroirsOuverts.jpeg",
  chDressingBlancInterphone: "/photos/chantiers/chDressingBlancInterphone.jpeg",
  chCouloirBibliothequeChaleureux: "/photos/chantiers/chCouloirBibliothequeChaleureux.jpeg",
  chDressingBlancPoigneesBoisVerticales: "/photos/chantiers/chDressingBlancPoigneesBoisVerticales.jpeg",
  chEscalierBoisConstructionMarches: "/photos/chantiers/chEscalierBoisConstructionMarches.jpeg",
  chRangementChantierEncombre: "/photos/chantiers/chRangementChantierEncombre.jpeg",
  chCuisineBleuCanardVueDeux: "/photos/chantiers/chCuisineBleuCanardVueDeux.jpeg",
  chPorteCoulissanteClaustraChene3: "/photos/chantiers/chPorteCoulissanteClaustraChene3.jpeg",
  chEscalierOuvertConstruction: "/photos/chantiers/chEscalierOuvertConstruction.jpeg",
  chCuisineNoireSkylightFinie: "/photos/chantiers/chCuisineNoireSkylightFinie.jpeg",
  chVasqueMarbreVanite: "/photos/chantiers/chVasqueMarbreVanite.jpeg",
  chDressingEntreeNoyerChantier: "/photos/chantiers/chDressingEntreeNoyerChantier.jpeg",
  chEntreeDressingNoyerPorte: "/photos/chantiers/chEntreeDressingNoyerPorte.jpeg",
  chGrilleAerationMdfAtelier2: "/photos/chantiers/chGrilleAerationMdfAtelier2.jpeg",
  chDressingNoyerAngleDeuxPortes: "/photos/chantiers/chDressingNoyerAngleDeuxPortes.jpeg",
  chCuisineNoireSejourFinie: "/photos/chantiers/chCuisineNoireSejourFinie.jpeg",
  chCouloirParquetChevronsPorteBois: "/photos/chantiers/chCouloirParquetChevronsPorteBois.jpeg",
  chDetailTiroirMainOuverture: "/photos/chantiers/chDetailTiroirMainOuverture.jpeg",
  chBibliothequeBlancheVitreeChantier: "/photos/chantiers/chBibliothequeBlancheVitreeChantier.jpeg",
  chNicheBoisAlcoveFinie: "/photos/chantiers/chNicheBoisAlcoveFinie.jpeg",
  chCouloirPorteBleueNoyer: "/photos/chantiers/chCouloirPorteBleueNoyer.jpeg",
  chCuisineBlanchePendantsFinie: "/photos/chantiers/chCuisineBlanchePendantsFinie.jpeg",
  chDressingMiroirCouloir: "/photos/chantiers/chDressingMiroirCouloir.jpeg",
  chEtagereMuraleFenetreChantier: "/photos/chantiers/chEtagereMuraleFenetreChantier.jpeg",
  chEtagereMuraleMainOuvriere: "/photos/chantiers/chEtagereMuraleMainOuvriere.jpeg",
  chDressingBlancCarcasseCrochets: "/photos/chantiers/chDressingBlancCarcasseCrochets.jpeg",
  chCuisineAnthraciteCarreauxVue2: "/photos/chantiers/chCuisineAnthraciteCarreauxVue2.jpeg",
  chCuisineAnthraciteGalerie: "/photos/chantiers/chCuisineAnthraciteGalerie.jpeg",
  chArmoireVitreeVerreDepoli: "/photos/chantiers/chArmoireVitreeVerreDepoli.jpeg",
  chDressingSousPenteTiroirs2: "/photos/chantiers/chDressingSousPenteTiroirs2.jpeg",
  chNicheArrondieRubanBleu: "/photos/chantiers/chNicheArrondieRubanBleu.jpeg",
  chFenetreBoisDecorativeChantier: "/photos/chantiers/chFenetreBoisDecorativeChantier.jpeg",
  chPanneauKraftEchelleChantier: "/photos/chantiers/chPanneauKraftEchelleChantier.jpeg",
  chCouloirDressingToilettes: "/photos/chantiers/chCouloirDressingToilettes.jpeg",

  /* Photos envoyées directement par le client (30/08/2026) pour le dossier
     d'ouverture de mur porteur — même chantier que le dossier bureau d'études
     anonymisé (voir public/photos/etudes/). */
  chDemolitionDegagementVersSejour: "/photos/chantiers/chDemolitionDegagementVersSejour.jpeg",
  chDemolitionLattisPlatreOuverture: "/photos/chantiers/chDemolitionLattisPlatreOuverture.jpeg",
  chPoutreAcierAngleSoudeVue1: "/photos/chantiers/chPoutreAcierAngleSoudeVue1.jpeg",
  chPoutreAcierProfilVueLongue: "/photos/chantiers/chPoutreAcierProfilVueLongue.jpeg",
} as const;

/* Décline une URL Unsplash (w=1600) en srcset 480/768/1200/1600 —
   transposition du cahier images V3 §3.2. Les fichiers locaux (une seule
   variante servie) ne produisent pas de srcset. */
export const srcSetOf = (url: string) =>
  url.includes("w=1600")
    ? [480, 768, 1200, 1600].map((w) => `${url.replace(/w=1600/, `w=${w}`)} ${w}w`).join(", ")
    : undefined;
